### ISSUE TITLE
[ObjC] FSharp binding fails in most basic cases

### ISSUE THREAD

**Issue by yasirmturk** [mono/Embeddinator-4000#549] opened 2017-11-24 15:21 UTC
$ mono objcgen/bin/Debug/objcgen.exe --platform=iOS --target=framework --outdir=output -c --debug /Users/punchee/Documents/teo/projects/exformatics/src/DCRGraphsNet/Engine/Core/bin/Debug/FSharp.Core.dll 
Parsing assemblies...
	Parsed '/Users/punchee/Documents/teo/projects/exformatics/src/DCRGraphsNet/Engine/Core/bin/Debug/FSharp.Core.dll'
Processing assemblies...
EM0000: Unexpected error - Please fill a bug report at https://github.com/mono/Embeddinator-4000/issues
System.NullReferenceException: Object reference not set to an instance of an object
  at Embeddinator.ObjC.NameGenerator.GetExtendedParameterName (IKVM.Reflection.ParameterInfo p, IKVM.Reflection.ParameterInfo[] parameters) [0x00025] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.ProcessedMethod.GetObjcSignature (System.String objName, System.Boolean isExtension) [0x00164] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.ProcessedMethod.ComputeSignatures () [0x00001] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.ProcessedMemberWithParameters.set_FirstDefaultParameter (System.Int32 value) [0x00008] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.ProcessedMethod..ctor (IKVM.Reflection.MethodInfo method, Embeddinator.ObjC.Processor processor) [0x00026] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.ObjCProcessor+<GetMethods>d__16.MoveNext () [0x0058d] in <a99569a8a21045778cc3528febf516c2>:0 
  at System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32& length) [0x0009f] in <3fb92ec709f44a579da6a23087df403d>:0 
  at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x00022] in <3fb92ec709f44a579da6a23087df403d>:0 
  at System.Linq.OrderedEnumerable`1[TElement].ToList () [0x00000] in <3fb92ec709f44a579da6a23087df403d>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <3fb92ec709f44a579da6a23087df403d>:0 
  at Embeddinator.ObjC.ObjCProcessor.Process (Embeddinator.ObjC.ProcessedType pt) [0x00100] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.Processor.Process (Embeddinator.ObjC.ProcessedAssembly a) [0x00102] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.Processor.Process (System.Collections.Generic.IEnumerable`1[T] input) [0x0007f] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.ObjCProcessor.Process (System.Collections.Generic.IEnumerable`1[T] input) [0x00001] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.Embedder.Generate (System.Collections.Generic.List`1[T] args) [0x000fc] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.Driver.Main2 (System.String[] args) [0x002f0] in <a99569a8a21045778cc3528febf516c2>:0 
  at Embeddinator.ObjC.Driver.Main (System.String[] args) [0x00002] in <a99569a8a21045778cc3528febf516c2>:0

**Comment by chamons** [comment] 2018-03-19 20:14
Full Log: https://gist.github.com/chamons/be64a2b24c4e4f090695f4d22dd85a0c

It appears we are crashing while processing this.

Processing Type: Microsoft_FSharp_Core_CompilerServices_ITypeProvider

May I ask what us case requires FSharp.Core.dll to be embedded?

**Comment by chamons** [comment] 2018-03-19 21:41
Possible duplicate of https://github.com/mono/Embeddinator-4000/issues/349

**Comment by yasirmturk** [comment] 2018-03-20 08:36
FSharp.Core.dll is dependency of .net portable libraries.. plz let me know if there are other work arounds

**Comment by yasirmturk** [comment] 2018-03-20 08:41
what i was looking to achieve 
https://forums.xamarin.com/discussion/100320/create-a-xamarin-library-which-can-be-consume-by-native-ios-android-applications
https://forums.xamarin.com/discussion/52727/use-a-xamarin-library-in-native-ios-android-apps

**Comment by yasirmturk** [comment] 2018-03-20 08:43
Also, i am open to hybrid solution which does not re-compile the xamarin libraries but may be use the mono runtime and provide some wrapper or RPC ??
http://www.mono-project.com/docs/advanced/embedding/

**Comment by chamons** [comment] 2018-03-20 14:47
Let's step back - What library are you trying to wrap? It may be a dependency, but I don't think we have to necessarily wrap it.

**Comment by chamons** [comment] 2018-03-21 20:01
Nevermind, I've been able to reproduce issues while binding the most trivial F# library into objc.

**Comment by yasirmturk** [comment] 2018-03-22 06:33
Yup thats it :)

**Comment by chamons** [comment] 2018-03-22 14:18
I have a patch that appears to work, and am porting F# tests to go along with it. I expect a PR sometime today.

**Closed** 2018-04-02 15:18 UTC
Labels: objc
