### ISSUE TITLE
Can't get .Net Embedding's objcgen.exe to convert my Visual Studio 2019 Xamarin.IOS project on Windows for my Xcode project on MacOS

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#761] opened 2020-03-02 16:39 UTC
### Steps to Reproduce

1. I create a hello world Xamarin.ios class library project.
2. I add Nuget Embeddinator 4000.
3. I build it on Visual Studio 2019 on Windows 10.
4. But when I run objcgen.exe to do the Embeddinator conversion, I get the error below..
2. 
3. 

### Actual Behavior

C:\Users\Doug\.nuget\packages\embeddinator-4000\0.4.0\tools\objcgen.exe --gen=Obj-C --platform=ios --compile --debug  --verbose `embedinnator2 class lib.dll'
Parsing assemblies...
        Parsed 'embedinnator2 class lib.dll'
Processing assemblies...
Processing: 1 assemblies
Processing Assembly: embedinnator2 class lib
Processing Type: embedinnator2_class_lib_Class1
TypeMapper Register: System.Void .ctor() init
        1 types found
Generating binding code...
Begin Generator
Generating Assembly: embedinnator2 class lib
Generating Type: embedinnator2_class_lib_Class1
        Generated: .\bindings.h
        Generated: .\bindings-private.h
        Generated: .\bindings.m
        Generated: .\bindings.xml
        Generated: .\embeddinator.h
        Generated: .\glib.h
        Generated: .\mono_embeddinator.h
        Generated: .\mono-support.h
        Generated: .\objc-support.h
        Generated: .\glib.c
        Generated: .\mono_embeddinator.c
        Generated: .\objc-support.m
        Generated: .\Make.config

Compiling binding code...

EM0000: Unexpected error - Please fill a bug report at https://github.com/mono/Embeddinator-4000/issues
System.NullReferenceException: Object reference not set to an instance of an object.

   at Embeddinator.ObjC.SystemCheck.VerifyMono()
   at Embeddinator.ObjC.Embedder.VerifyDependencies()
   at Embeddinator.ObjC.Embedder.Compile()
   at Embeddinator.ObjC.Driver.Main2(String[] args)
   at Embeddinator.ObjC.Driver.Main(String[] args)
Debug Log:
Processing: 1 assemblies
Processing Assembly: embedinnator2 class lib
Processing Type: embedinnator2_class_lib_Class1
TypeMapper Register: System.Void .ctor() init
Begin Generator
Generating Assembly: embedinnator2 class lib
Generating Type: embedinnator2_class_lib_Class1

### Environment
Visual Studio 2019 Pro running Windows 10

```
```

### Build Logs
C:\Users\Doug\.nuget\packages\embeddinator-4000\0.4.0\tools\objcgen.exe --gen=Obj-C --platform=ios --compile --debug  --verbose `embedinnator2 class lib.dll'
Parsing assemblies...
        Parsed 'embedinnator2 class lib.dll'
Processing assemblies...
Processing: 1 assemblies
Processing Assembly: embedinnator2 class lib
Processing Type: embedinnator2_class_lib_Class1
TypeMapper Register: System.Void .ctor() init
        1 types found
Generating binding code...
Begin Generator
Generating Assembly: embedinnator2 class lib
Generating Type: embedinnator2_class_lib_Class1
        Generated: .\bindings.h
        Generated: .\bindings-private.h
        Generated: .\bindings.m
        Generated: .\bindings.xml
        Generated: .\embeddinator.h
        Generated: .\glib.h
        Generated: .\mono_embeddinator.h
        Generated: .\mono-support.h
        Generated: .\objc-support.h
        Generated: .\glib.c
        Generated: .\mono_embeddinator.c
        Generated: .\objc-support.m
        Generated: .\Make.config

Compiling binding code...

EM0000: Unexpected error - Please fill a bug report at https://github.com/mono/Embeddinator-4000/issues
System.NullReferenceException: Object reference not set to an instance of an object.

   at Embeddinator.ObjC.SystemCheck.VerifyMono()
   at Embeddinator.ObjC.Embedder.VerifyDependencies()
   at Embeddinator.ObjC.Embedder.Compile()
   at Embeddinator.ObjC.Driver.Main2(String[] args)
   at Embeddinator.ObjC.Driver.Main(String[] args)
Debug Log:
Processing: 1 assemblies
Processing Assembly: embedinnator2 class lib
Processing Type: embedinnator2_class_lib_Class1
TypeMapper Register: System.Void .ctor() init
Begin Generator
Generating Assembly: embedinnator2 class lib
Generating Type: embedinnator2_class_lib_Class1

**Comment by chamons** [comment] 2020-03-03 15:40
I believe this is a duplicate of https://github.com/mono/Embeddinator-4000/issues/756.

The Embeddinator-4000 tool does not support remote building on a mac from Windows, and requires clang to build the native library.

**Closed by chamons** 2020-03-03 15:40 UTC

**Comment by dbell-movano** [comment] 2020-03-06 15:21
What is "clang"?

**Comment by chamons** [comment] 2020-03-06 15:25
[Clang](https://en.wikipedia.org/wiki/Clang) is Apple's native compiler.
