### ISSUE TITLE
[java] generator fails on MonoGame.Framework.dll

### ISSUE THREAD

**Issue by jonathanpeppers** [mono/Embeddinator-4000#438] opened 2017-07-14 03:58 UTC
I just wanted to test a complex library, so I chose MonoGame.

To get it, just do:
```
nuget install MonoGame.Framework.Android
```
Then I ran Embeddinator on it with `--gen=Java --platform=Android -c` on `MonoGame.Framework.dll`.

First issue came up was a dictionary failure on a `ButtonState` enum, I think the fix for that is here: https://github.com/jonathanpeppers/Embeddinator-4000/commit/ed8d19de3d0ed1df2fbe6149c1463c0afcd78b53

But once past that, there are alot of compiler errors in the generated C:
```
Compiling binding code...
        In file included from test/MonoGame.Framework.h:12:0,
                 from test/MonoGame.Framework.c:7:
test/mscorlib.h:90:24: warning: type defaults to 'int' in declaration of 'System_EventArgs_get_Empty'
 MONO_EMBEDDINATOR_API  System_EventArgs_get_Empty();
                        ^
test/mscorlib.h:91:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_EventArgs_set_Empty( value);
 ^
test/mscorlib.h:150:24: warning: type defaults to 'int' in declaration of 'System_IO_Stream_get_Null'
 MONO_EMBEDDINATOR_API  System_IO_Stream_get_Null();
                        ^
test/mscorlib.h:151:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_IO_Stream_set_Null( value);
 ^
test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_JoystickState_get_Buttons':
test/MonoGame.Framework.c:59130:5: error: 'class_Microsoft_Xna_Framework_Input_ButtonState' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_ButtonState = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.ButtonState");
     ^
test/MonoGame.Framework.c:59130:5: note: each undeclared identifier is reported only once for each function it appears in
test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_KeyboardState_new':
test/MonoGame.Framework.c:59346:5: error: 'class_Microsoft_Xna_Framework_Input_Keys' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_Keys = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.Keys");
     ^
In file included from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/appdomain.h:16:0,
                 from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/jit/jit.h:12,
                 from test/mono-support.h:187,
                 from test/mono_embeddinator.h:32,
                 from test/MonoGame.Framework.h:10,
                 from test/MonoGame.Framework.c:7:
/Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/object.h:57:8: error: incompatible types when assigning to type 'Microsoft_Xna_Framework_Input_Keys' from type 'enum Microsoft_Xna_Framework_Input_Keys *'
   *__p = (value); \
        ^
test/MonoGame.Framework.c:59352:9: note: in expansion of macro 'mono_array_set'
         mono_array_set(__keys_array, Microsoft_Xna_Framework_Input_Keys, __i, &__keys_array_element);
         ^
test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_KeyboardState_new_1':
test/MonoGame.Framework.c:59388:5: error: 'class_Microsoft_Xna_Framework_Input_Keys' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_Keys = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.Keys");
     ^
In file included from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/appdomain.h:16:0,
                 from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/jit/jit.h:12,
                 from test/mono-support.h:187,
                 from test/mono_embeddinator.h:32,
                 from test/MonoGame.Framework.h:10,
                 from test/MonoGame.Framework.c:7:
/Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/object.h:57:8: error: incompatible types when assigning to type 'Microsoft_Xna_Framework_Input_Keys' from type 'enum Microsoft_Xna_Framework_Input_Keys *'
   *__p = (value); \
        ^
test/MonoGame.Framework.c:59394:9: note: in expansion of macro 'mono_array_set'
         mono_array_set(__keys_array, Microsoft_Xna_Framework_Input_Keys, __i, &__keys_array_element);
         ^
test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_KeyboardState_GetPressedKeys':
test/MonoGame.Framework.c:59580:5: error: 'class_Microsoft_Xna_Framework_Input_Keys' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_Keys = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.Keys");
     ^
In file included from test/mscorlib.h:12:0,
                 from test/mscorlib.c:7:
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
                                                                                                                         ^
In file included from test/mscorlib.c:7:0:
test/mscorlib.h:90:24: warning: type defaults to 'int' in declaration of 'System_EventArgs_get_Empty'
 MONO_EMBEDDINATOR_API  System_EventArgs_get_Empty();
                        ^
test/mscorlib.h:91:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_EventArgs_set_Empty( value);
 ^
test/mscorlib.h:150:24: warning: type defaults to 'int' in declaration of 'System_IO_Stream_get_Null'
 MONO_EMBEDDINATOR_API  System_IO_Stream_get_Null();
                        ^
test/mscorlib.h:151:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_IO_Stream_set_Null( value);
 ^
test/mscorlib.c:906:2: warning: return type defaults to 'int'
  System_EventArgs_get_Empty()
  ^
test/mscorlib.c: In function 'System_EventArgs_get_Empty':
test/mscorlib.c:916:5: warning: 'return' with no value, in function returning non-void
     return ;
     ^
test/mscorlib.c: In function 'System_EventArgs_set_Empty':
test/mscorlib.c:919:6: warning: type of 'value' defaults to 'int'
 void System_EventArgs_set_Empty( value)
      ^
test/mscorlib.c:928:21: error: expected expression before ';' token
     void* __value = ;
                     ^
test/mscorlib.c: At top level:
test/mscorlib.c:2457:2: warning: return type defaults to 'int'
  System_IO_Stream_get_Null()
  ^
test/mscorlib.c: In function 'System_IO_Stream_get_Null':
test/mscorlib.c:2467:5: warning: 'return' with no value, in function returning non-void
     return ;
     ^
test/mscorlib.c: In function 'System_IO_Stream_set_Null':
test/mscorlib.c:2470:6: warning: type of 'value' defaults to 'int'
 void System_IO_Stream_set_Null( value)
      ^
test/mscorlib.c:2479:21: error: expected expression before ';' token
     void* __value = ;
                     ^
In file included from test/mscorlib.h:12:0,
                 from test/Mono.Android.h:12,
                 from test/Mono.Android.c:7:
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
                                                                                                                         ^
In file included from test/Mono.Android.h:12:0,
                 from test/Mono.Android.c:7:
test/mscorlib.h:90:24: warning: type defaults to 'int' in declaration of 'System_EventArgs_get_Empty'
 MONO_EMBEDDINATOR_API  System_EventArgs_get_Empty();
                        ^
test/mscorlib.h:91:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_EventArgs_set_Empty( value);
 ^
test/mscorlib.h:150:24: warning: type defaults to 'int' in declaration of 'System_IO_Stream_get_Null'
 MONO_EMBEDDINATOR_API  System_IO_Stream_get_Null();
                        ^
test/mscorlib.h:151:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_IO_Stream_set_Null( value);
 ^
In file included from test/mscorlib.h:12:0,
                 from test/Java.Interop.h:12,
                 from test/Java.Interop.c:7:
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
                                                                                                                         ^
In file included from test/Java.Interop.h:12:0,
                 from test/Java.Interop.c:7:
test/mscorlib.h:90:24: warning: type defaults to 'int' in declaration of 'System_EventArgs_get_Empty'
 MONO_EMBEDDINATOR_API  System_EventArgs_get_Empty();
                        ^
test/mscorlib.h:91:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_EventArgs_set_Empty( value);
 ^
test/mscorlib.h:150:24: warning: type defaults to 'int' in declaration of 'System_IO_Stream_get_Null'
 MONO_EMBEDDINATOR_API  System_IO_Stream_get_Null();
                        ^
test/mscorlib.h:151:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_IO_Stream_set_Null( value);
 ^
In file included from test/mscorlib.h:12:0,
                 from test/Mono.Android.h:12,
                 from test/OpenTK-1.0.h:12,
                 from test/OpenTK-1.0.c:7:
test/MonoGame.Framework.h:2222:23: error: unknown type name 'OpenTK_Graphics_ES20_TextureTarget'
 MONO_EMBEDDINATOR_API OpenTK_Graphics_ES20_TextureTarget Microsoft_Xna_Framework_Graphics_IRenderTarget_get_GLTarget(Microsoft_Xna_Framework_Graphics_IRenderTarget* object);
                       ^
test/MonoGame.Framework.h:2231:23: error: unknown type name 'OpenTK_Graphics_ES20_TextureTarget'
 MONO_EMBEDDINATOR_API OpenTK_Graphics_ES20_TextureTarget Microsoft_Xna_Framework_Graphics_IRenderTarget_GetFramebufferTarget(Microsoft_Xna_Framework_Graphics_IRenderTarget* object, Microsoft_Xna_Framework_Graphics_RenderTargetBinding* renderTargetBinding);
                       ^
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
                                                                                                                         ^
In file included from test/Mono.Android.h:12:0,
                 from test/OpenTK-1.0.h:12,
                 from test/OpenTK-1.0.c:7:
test/mscorlib.h:90:24: warning: type defaults to 'int' in declaration of 'System_EventArgs_get_Empty'
 MONO_EMBEDDINATOR_API  System_EventArgs_get_Empty();
                        ^
test/mscorlib.h:91:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_EventArgs_set_Empty( value);
 ^
test/mscorlib.h:150:24: warning: type defaults to 'int' in declaration of 'System_IO_Stream_get_Null'
 MONO_EMBEDDINATOR_API  System_IO_Stream_get_Null();
                        ^
test/mscorlib.h:151:1: warning: parameter names (without types) in function declaration
 MONO_EMBEDDINATOR_API void System_IO_Stream_set_Null( value);
 ^

Failed to compile generated code.
```

No rush on this, I just did this to try to break stuff. Some of the issues here might need to be split out into different things.

Some things I see:
- Might be more issues with enums
- Maybe issues with static field/properties that return objects of themselves like `EventArgs.Empty`

If the generators could make it past a decent-sized library like this, we should be in good shape!

**Comment by jonathanpeppers** [comment] 2017-07-18 19:50
Just a note on this, after the above 2 PRs we have alot less errors here now:
```
Compiling binding code...
        test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_JoystickState_get_Buttons':
test/MonoGame.Framework.c:59126:5: error: 'class_Microsoft_Xna_Framework_Input_ButtonState' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_ButtonState = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.ButtonState");
     ^
test/MonoGame.Framework.c:59126:5: note: each undeclared identifier is reported only once for each function it appears in
test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_KeyboardState_new':
test/MonoGame.Framework.c:59342:5: error: 'class_Microsoft_Xna_Framework_Input_Keys' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_Keys = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.Keys");
     ^
In file included from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/appdomain.h:16:0,
                 from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/jit/jit.h:12,
                 from test/mono-support.h:187,
                 from test/mono_embeddinator.h:32,
                 from test/MonoGame.Framework.h:10,
                 from test/MonoGame.Framework.c:7:
/Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/object.h:57:8: error: incompatible types when assigning to type 'Microsoft_Xna_Framework_Input_Keys' from type 'enum Microsoft_Xna_Framework_Input_Keys *'
   *__p = (value); \
        ^
test/MonoGame.Framework.c:59348:9: note: in expansion of macro 'mono_array_set'
         mono_array_set(__keys_array, Microsoft_Xna_Framework_Input_Keys, __i, &__keys_array_element);
         ^
test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_KeyboardState_new_1':
test/MonoGame.Framework.c:59384:5: error: 'class_Microsoft_Xna_Framework_Input_Keys' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_Keys = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.Keys");
     ^
In file included from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/appdomain.h:16:0,
                 from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/jit/jit.h:12,
                 from test/mono-support.h:187,
                 from test/mono_embeddinator.h:32,
                 from test/MonoGame.Framework.h:10,
                 from test/MonoGame.Framework.c:7:
/Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/object.h:57:8: error: incompatible types when assigning to type 'Microsoft_Xna_Framework_Input_Keys' from type 'enum Microsoft_Xna_Framework_Input_Keys *'
   *__p = (value); \
        ^
test/MonoGame.Framework.c:59390:9: note: in expansion of macro 'mono_array_set'
         mono_array_set(__keys_array, Microsoft_Xna_Framework_Input_Keys, __i, &__keys_array_element);
         ^
test/MonoGame.Framework.c: In function 'Microsoft_Xna_Framework_Input_KeyboardState_GetPressedKeys':
test/MonoGame.Framework.c:59576:5: error: 'class_Microsoft_Xna_Framework_Input_Keys' undeclared (first use in this function)
     class_Microsoft_Xna_Framework_Input_Keys = mono_class_from_name(__MonoGame_Framework_dll_image, "", "Microsoft.Xna.Framework.Input.Keys");
     ^
In file included from test/mscorlib.h:12:0,
                 from test/mscorlib.c:7:
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
                                                                                                                         ^
In file included from test/mscorlib.h:12:0,
                 from test/Mono.Android.h:12,
                 from test/Mono.Android.c:7:
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
                                                                                                                         ^
In file included from test/mscorlib.h:12:0,
                 from test/Java.Interop.h:12,
                 from test/Java.Interop.c:7:
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
                                                                                                                         ^
In file included from test/mscorlib.h:12:0,
                 from test/Mono.Android.h:12,
                 from test/OpenTK-1.0.h:12,
                 from test/OpenTK-1.0.c:7:
test/MonoGame.Framework.h:2222:23: error: unknown type name 'OpenTK_Graphics_ES20_TextureTarget'
 MONO_EMBEDDINATOR_API OpenTK_Graphics_ES20_TextureTarget Microsoft_Xna_Framework_Graphics_IRenderTarget_get_GLTarget(Microsoft_Xna_Framework_Graphics_IRenderTarget* object);
                       ^
test/MonoGame.Framework.h:2231:23: error: unknown type name 'OpenTK_Graphics_ES20_TextureTarget'
 MONO_EMBEDDINATOR_API OpenTK_Graphics_ES20_TextureTarget Microsoft_Xna_Framework_Graphics_IRenderTarget_GetFramebufferTarget(Microsoft_Xna_Framework_Graphics_IRenderTarget* object, Microsoft_Xna_Framework_Graphics_RenderTargetBinding* renderTargetBinding);
                       ^
test/MonoGame.Framework.h:3623:121: error: unknown type name 'System_IO_SeekOrigin'
 MONO_EMBEDDINATOR_API int64_t MonoGame_Utilities_ZlibStream_Seek(MonoGame_Utilities_ZlibStream* object, int64_t offset, System_IO_SeekOrigin origin);
```

**Comment by tritao** [comment] 2017-07-21 00:35
Next issue here seems to be caused by a conflict in generated code:

```
Compiling binding code...
        mg/MonoGame.Framework.c:51078:53: error: redefinition of 'Microsoft_Xna_Framework_Graphics_VertexPosition_get_VertexDeclaration'
 Microsoft_Xna_Framework_Graphics_VertexDeclaration* Microsoft_Xna_Framework_Graphics_VertexPosition_get_VertexDeclaration()
                                                     ^
mg/MonoGame.Framework.c:50937:53: note: previous definition of 'Microsoft_Xna_Framework_Graphics_VertexPosition_get_VertexDeclaration' was here
 Microsoft_Xna_Framework_Graphics_VertexDeclaration* Microsoft_Xna_Framework_Graphics_VertexPosition_get_VertexDeclaration(Microsoft_Xna_Framework_Graphics_VertexPosition* object)                                                
```

which is cased by:

```
	public struct VertexPosition : IVertexType
	{
        [DataMember]
		public Vector3 Position;

		public static readonly VertexDeclaration VertexDeclaration;

                ...

		VertexDeclaration IVertexType.VertexDeclaration
                {
			get { return VertexDeclaration; }
		}
```

**Comment by tritao** [comment] 2017-07-26 15:44
All generation issues have been fixed.

**Comment by tritao** [comment] 2017-07-28 16:36
Getting close.

```
Compiling binding code...        
/Users/joao/Dev/MonoEmbeddinator4000/build/lib/Debug/mg/monogame_framework/opengl/IGraphicsContextImpl.java:56: error: cannot find symbol
        monogame_framework.Native_MonoGame_Framework.INSTANCE.System_IDisposable_Dispose(__object);
                                                             ^
  symbol:   method System_IDisposable_Dispose(Pointer)
  location: variable INSTANCE of type Native_MonoGame_Framework
/Users/joao/Dev/MonoEmbeddinator4000/build/lib/Debug/mg/monogame_framework/microsoft/xna/framework/GameWindow.java:14: error: GameWindow is not abstract and does not override abstract method endScreenDeviceChange(String,int,int) in GameWindow
public class GameWindow {
       ^
/Users/joao/Dev/MonoEmbeddinator4000/build/lib/Debug/mg/mscorlib/system/io/Stream.java:14: error: Stream is not abstract and does not override abstract method setLength(long) in Stream
public class Stream extends mscorlib.system.MarshalByRefObject implements mscorlib.system.IDisposable {
       ^
/Users/joao/Dev/MonoEmbeddinator4000/build/lib/Debug/mg/opentk_1_0/opentk/platform/IGameWindowImpl.java:180: error: cannot find symbol
        opentk_1_0.Native_OpenTK_1_0.INSTANCE.System_IDisposable_Dispose(__object);
                                             ^
  symbol:   method System_IDisposable_Dispose(Pointer)
  location: variable INSTANCE of type Native_OpenTK_1_0
/Users/joao/Dev/MonoEmbeddinator4000/build/lib/Debug/mg/opentk_1_0/opentk/INativeWindowImpl.java:156: error: cannot find symbol
        opentk_1_0.Native_OpenTK_1_0.INSTANCE.System_IDisposable_Dispose(__object);
                                             ^
  symbol:   method System_IDisposable_Dispose(Pointer)
  location: variable INSTANCE of type Native_OpenTK_1_0
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
```

**Comment by tritao** [comment] 2017-08-18 16:53
Should be fixed once https://github.com/mono/Embeddinator-4000/pull/488 is merged.

**Closed** 2017-08-29 12:28 UTC
Labels: bug
