### ISSUE TITLE
IKVM issue when trying to e4k mscorlib.dll

### ISSUE THREAD

**Issue by VincentDondain** [mono/Embeddinator-4000#225] opened 2017-05-01 19:06 UTC
Here's the command and exception: https://gist.github.com/VincentDondain/46b3ed7f4e73799a46be83914de47c9d

I'm using the latest version of `e4k/objc` branch: Embeddinator-4000 v0.1 (objc: 32ea4c0) and Mono version 5.2.0.48 (master/645d38b).

**Comment by spouliot** [comment] 2017-05-02 01:38
@VincentDondain I don't have that 4.8.1 version of mscorlib and I'm getting different results. It would be useful to extract a test case so it can be added to our test suite.

**Comment by VincentDondain** [comment] 2017-05-02 14:05
FYI same issue with 5.2.0: https://gist.github.com/VincentDondain/9f6e4477a89691dea5abc88e191ca371

**Comment by VincentDondain** [comment] 2017-05-03 20:39
Worked with `/Library/Frameworks/Mono.framework/Versions/4.9.3/lib/mono/4.5/mscorlib.dll`

**Comment by chamons** [comment] 2017-05-09 19:34
I am getting same exact issue with:

https://www.dropbox.com/s/hj3nhdt23lpjx6b/mscorlib_ikvm.dll?dl=0

It appears we're calling:

			switch (t.Namespace) {

in objcgen/objcprocessor.cs:50

and here:
```
IKVM.Reflection.Reader.GenericTypeParameter.get_Namespace() in /Users/donblas/Programming/Embeddinator-4000/external/ikvm/reflect/Reader/GenericTypeParameter.cs:287
IKVM.Reflection.ElementHolderType.get_Namespace() in /Users/donblas/Programming/Embeddinator-4000/external/ikvm/reflect/Type.cs:2303
ObjC.ObjCProcessor.IsSupported(IKVM.Reflection.ArrayType t) in /Users/donblas/Programming/Embeddinator-4000/objcgen/objcprocessor.cs:50
```

		public override string Namespace
		{
			get { return DeclaringType.Namespace; }
		}

DeclaringType is null for Array.Sort

**Comment by spouliot** [comment] 2017-05-09 19:58
weird, it might be worth checking if we're using the latest IKVM.Reflection - that might already be fixed (along other things).

**Comment by timrisi** [comment] 2017-05-11 00:23
I was getting the original error when I started, but am unable to reproduce it now.  

I did get to another error: https://gist.github.com/timrisi/5e79d4447700ee7c7c403239b0f165cd which should be fixed by PR#316.  

After fixing that, I hit another error (NotImplementedException) for a method that passes a byte array by reference (Issue #314, @dalexsoto is going to fix).  Temporarily changing that to a warning let me bind mscorlib successfully.

**Comment by dalexsoto** [comment] 2017-05-11 00:33
Yep on it!

**Comment by timrisi** [comment] 2017-05-11 17:09
Between PR316 and issue #314 having been fixed, I'm now ablet o generate mscorlib without any errors

**Closed by timrisi** 2017-05-11 17:09 UTC
Labels: bug

**Comment by lemonmojo** [comment] 2017-08-16 19:03
With today's master, and Mono 5.4.0.135 I'm unable to successfully create and compile a binding for mscorlib.

I'm invoking objcgen like this: `mono objcgen.exe --platform=macOS-full --abi=x86_64 --target=framework -c -o ./ /Library/Frameworks/Mono.framework/Libraries/mono/4.5/mscorlib.dll`.

Generating the binding code actually succeeds but compiling it then fails with lots of errors and the compiler finally gives up.

```
In file included from ./bindings.m:1:
./bindings.h:293:16: error: expected ';' after @class
@class NSString *;
               ^
               ;
./bindings.h:293:18: error: expected identifier or '('
@class NSString *;
                 ^
./bindings.h:351:8: error: expected identifier
@class bool;
       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/include/stdbool.h:31:14: note: expanded from macro 'bool'
#define bool _Bool
             ^
In file included from ./bindings.m:1:
./bindings.h:352:8: error: expected identifier
@class unsigned char;
       ^
./bindings.h:353:8: error: expected identifier
@class unsigned short;
       ^
./bindings.h:364:23: error: expected ';' after @class
@class NSDecimalNumber *;
                      ^
                      ;
./bindings.h:364:25: error: expected identifier or '('
@class NSDecimalNumber *;
                        ^
./bindings.h:394:8: error: expected identifier
@class double;
       ^
./bindings.h:414:8: error: expected identifier
@class short;
       ^
./bindings.h:415:8: error: expected identifier
@class int;
       ^
./bindings.h:416:8: error: expected identifier
@class long long;
       ^
./bindings.h:687:8: error: expected identifier
@class signed char;
       ^
./bindings.h:843:8: error: expected identifier
@class float;
       ^
./bindings.h:889:8: error: expected identifier
@class unsigned short;
       ^
./bindings.h:890:8: error: expected identifier
@class unsigned int;
       ^
./bindings.h:891:8: error: expected identifier
@class unsigned long long;
       ^
./bindings.h:895:8: error: expected identifier
@class void;
       ^
./bindings.h:1752:34: error: redefinition of 'System_Globalization_TimeSpanStyles'
typedef NS_OPTIONS(unsigned int, System_Globalization_TimeSpanStyles) {
                                 ^
./bindings.h:1744:34: note: previous definition is here
typedef NS_OPTIONS(unsigned int, System_Globalization_TimeSpanStyles) {
                                 ^
./bindings.h:1753:2: error: redefinition of enumerator 'System_Globalization_TimeSpanStylesAssumeNegative'
        System_Globalization_TimeSpanStylesAssumeNegative = 0x1,
        ^
./bindings.h:1745:2: note: previous definition is here
        System_Globalization_TimeSpanStylesAssumeNegative = 0x1,
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```
