### ISSUE TITLE
Attempted to run objcgen against an F# dll, output asked me to file a bug.

### ISSUE THREAD

**Issue by kylekurz** [mono/Embeddinator-4000#349] opened 2017-05-17 15:50 UTC
Not sure if you expect this to be supported yet, but the summary sounds like you think it *should* work for F# code.

```
kkurz@HacBook-Pro:~/Git/softphones/Platform.ios.fsharp (development)$ objcgen bin/Debug/Platform.ios.fsharp.dll --target=framework --platform=iOS --outdir=output -c --debug
Creating output directory `/Users/kkurz/Git/softphones/Platform.ios.fsharp/output`
Parsing assemblies...
	Parsed 'bin/Debug/Platform.ios.fsharp.dll'
Processing assemblies...
EM0000: Unexpected error - Please fill a bug report at https://github.com/mono/Embeddinator-4000/issues
System.NullReferenceException: Object reference not set to an instance of an object
  at IKVM.Reflection.Reader.GenericTypeParameter.get_Namespace () [0x00001] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/external/ikvm/reflect/Reader/GenericTypeParameter.cs:287 
  at IKVM.Reflection.ElementHolderType.get_Namespace () [0x00001] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/external/ikvm/reflect/Type.cs:2303 
  at ObjC.ObjCProcessor.IsSupported (IKVM.Reflection.Type t) [0x000cf] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/objcprocessor.cs:50 
  at ObjC.ObjCProcessor+<GetMethods>d__10.MoveNext () [0x001eb] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/objcprocessor.cs:157 
  at System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32& length) [0x0009f] in /private/tmp/source-mono-2017-04/bockbuild-2017-04/profiles/mono-mac-xamarin/build-root/mono-x64/external/corefx/src/Common/src/System/Collections/Generic/EnumerableHelpers.cs:128 
  at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x00022] in /private/tmp/source-mono-2017-04/bockbuild-2017-04/profiles/mono-mac-xamarin/build-root/mono-x64/external/corefx/src/System.Linq/src/System/Linq/Buffer.cs:40 
  at System.Linq.OrderedEnumerable`1[TElement].ToList () [0x00000] in /private/tmp/source-mono-2017-04/bockbuild-2017-04/profiles/mono-mac-xamarin/build-root/mono-x64/external/corefx/src/System.Linq/src/System/Linq/OrderedEnumerable.cs:59 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00015] in /private/tmp/source-mono-2017-04/bockbuild-2017-04/profiles/mono-mac-xamarin/build-root/mono-x64/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30 
  at ObjC.ObjCProcessor.Process (Embeddinator.ProcessedType pt) [0x0010e] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/objcprocessor.cs:270 
  at Embeddinator.Processor.Process (Embeddinator.ProcessedAssembly a) [0x000c6] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/processor.cs:61 
  at Embeddinator.Processor.Process (System.Collections.Generic.IEnumerable`1[T] input) [0x00074] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/processor.cs:32 
  at ObjC.ObjCProcessor.Process (System.Collections.Generic.IEnumerable`1[T] input) [0x00001] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/objcprocessor.cs:236 
  at Embeddinator.Embedder.Generate (System.Collections.Generic.List`1[T] args) [0x000f6] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/driver.cs:262 
  at Embeddinator.Driver.Main2 (System.String[] args) [0x00273] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/driver.cs:103 
  at Embeddinator.Driver.Main (System.String[] args) [0x00002] in /Users/builder/data/lanes/4879/ddb3ce5c/source/Embeddinator-4000/objcgen/driver.cs:51
```

**Comment by spouliot** [comment] 2017-05-17 18:31
Thanks for the report. This is a bug in `IKVM.Reflection`, it should not throw a `NullReferenceException`.

@tritao did you find out if mono's fork is the latest version ?

**Comment by tritao** [comment] 2017-05-17 18:39
@spouliot So there was some work around https://github.com/jfrijters/Managed.Reflection as an alternative for IKVM, but from what I gathered this work is now in limbo too as well as IKVM, so the our best bet is to cherry pick the needed fixes from upstream to get our fork up-to-date and maintain it ourselves going forward.

**Comment by realvictorprm** [comment] 2017-05-19 20:41
Hm, I'll take a look into this too.

**Comment by realvictorprm** [comment] 2017-06-05 21:44
Again, we need to fix this

**Comment by realvictorprm** [comment] 2017-06-05 21:45
Or rather I'll fix this because it's important that this library is compatible with F#.

**Comment by kylekurz** [comment] 2017-07-28 21:11
Swinging back around to this again, as I'm trying my hand at the E4k again this week. Still seeing the same errors, anyone ever decide if F# Reflection was going to be supported here?

**Comment by jonathanpeppers** [comment] 2017-07-28 21:21
To to give more info on what's failing in IKVM.Reflection:
```csharp
public override string Namespace
{
	get { return DeclaringType.Namespace; }
}
```

From the stack trace above, `DeclaringType` is returning null:
```csharp
public override Type DeclaringType
{
	get
	{
		int owner = module.GenericParam.records[index].Owner;
		return (owner >> 24) == TypeDefTable.Index ? module.ResolveType(owner) : null;
	}
}
```
I'm not familiar with IKVM.Reflection's codebase yet, so I can't say what is going wrong here.

Could someone paste some sample F# code that breaks this? Or is it *any* F# code? Even "hello world"?

**Comment by kylekurz** [comment] 2017-07-28 21:50
So, Hello World doesn't have the *same* error, but it's pretty obvious that there's a fundamental lack of F# support at this point. Not sure if this belongs here or in another ticket (Test project attached)...

> Kyles-Mac:HelloWorld kkurz$ objcgen -c --platform=iOS HelloWorld/bin/Debug/HelloWorld.dll
> Parsing assemblies...
> 	Parsed 'HelloWorld/bin/Debug/HelloWorld.dll'
> Processing assemblies...
> 	3 types found
> warning EM1011: Type `System.Object` is not generated because it lacks a native counterpart.
> warning EM1031: Method `Int32 CompareTo(System.Object, System.Collections.IComparer)` is not generated because of parameter type `System.Object` is not supported.
> warning EM1031: Method `Boolean Equals(System.Object, System.Collections.IEqualityComparer)` is not generated because of parameter type `System.Object` is not supported.
> Generating binding code...
> error EM0009: The feature `Converting type System.Collections.IEqualityComparer to mono code` is not currently supported by the tool
[HelloWorld.zip](https://github.com/mono/Embeddinator-4000/files/1184342/HelloWorld.zip)

**Comment by jonathanpeppers** [comment] 2017-07-31 18:53
Hi @kylekurz,

I tried your sample and it worked for me on Android: 
```
Jonathans-MBP:Release jonathanpeppers$ mono MonoEmbeddinator4000.exe --gen=Java --platform=Android -o fsharp /Users/jonathanpeppers/Downloads/HelloWorld/HelloWorld/bin/Debug/HelloWorld.dll -c
Parsing assemblies...
    Parsed 'HelloWorld.dll'
Processing assemblies...
Generating binding code...
    Generated: HelloWorld.h
    Generated: HelloWorld.c
    Generated: c-support.c
    Generated: c-support.h
    Generated: embeddinator.h
    Generated: glib.c
    Generated: glib.h
    Generated: mono-support.c
    Generated: mono-support.h
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...
Parsing assemblies...
    Parsed 'HelloWorld.dll'
    Parsed 'HelloWorld.dll'
Processing assemblies...
Generating binding code...
    Generated: helloworld/Script.java
    Generated: helloworld/MyModule.java
    Generated: helloworld/Native_HelloWorld.java
    Generating Java stubs...
Compiling binding code...
        /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home

    Linking assemblies...
        added manifest
adding: AndroidManifest.xml(in = 732) (out= 373)(deflated 49%)
adding: assets/(in = 0) (out= 0)(stored 0%)
adding: assets/assemblies/(in = 0) (out= 0)(stored 0%)
adding: assets/assemblies/FSharp.Core.dll(in = 1413632) (out= 432530)(deflated 69%)
adding: assets/assemblies/HelloWorld.dll(in = 8704) (out= 3212)(deflated 63%)
adding: assets/assemblies/HelloWorld.dll.mdb(in = 368) (out= 229)(deflated 37%)
adding: assets/assemblies/Java.Interop.dll(in = 81920) (out= 25367)(deflated 69%)
adding: assets/assemblies/Mono.Android.dll(in = 645120) (out= 171160)(deflated 73%)
adding: assets/assemblies/Mono.Android.Export.dll(in = 69632) (out= 27293)(deflated 60%)
adding: assets/assemblies/Mono.Security.dll(in = 173056) (out= 73874)(deflated 57%)
adding: assets/assemblies/mscorlib.dll(in = 1966080) (out= 691126)(deflated 64%)
adding: assets/assemblies/Resource.designer.dll(in = 3584) (out= 1345)(deflated 62%)
adding: assets/assemblies/System.Core.dll(in = 379904) (out= 150280)(deflated 60%)
adding: assets/assemblies/System.dll(in = 616448) (out= 254900)(deflated 58%)
adding: assets/assemblies/System.Runtime.Serialization.dll(in = 5120) (out= 1915)(deflated 62%)
adding: assets/assemblies/System.Xml.dll(in = 849408) (out= 311570)(deflated 63%)
adding: classes.jar(in = 1026042) (out= 954897)(deflated 6%)
adding: jni/(in = 0) (out= 0)(stored 0%)
adding: jni/arm64-v8a/(in = 0) (out= 0)(stored 0%)
adding: jni/arm64-v8a/libHelloWorld.so(in = 28776) (out= 8236)(deflated 71%)
adding: jni/arm64-v8a/libjnidispatch.so(in = 101976) (out= 38986)(deflated 61%)
adding: jni/arm64-v8a/libmonodroid.so(in = 153928) (out= 54019)(deflated 64%)
adding: jni/arm64-v8a/libmonosgen-2.0.so(in = 3098600) (out= 1289218)(deflated 58%)
adding: jni/armeabi/(in = 0) (out= 0)(stored 0%)
adding: jni/armeabi/libHelloWorld.so(in = 27400) (out= 7867)(deflated 71%)
adding: jni/armeabi/libjnidispatch.so(in = 102080) (out= 43951)(deflated 56%)
adding: jni/armeabi/libmonodroid.so(in = 141048) (out= 57312)(deflated 59%)
adding: jni/armeabi/libmonosgen-2.0.so(in = 3477484) (out= 1454975)(deflated 58%)
adding: jni/armeabi-v7a/(in = 0) (out= 0)(stored 0%)
adding: jni/armeabi-v7a/libHelloWorld.so(in = 27408) (out= 7882)(deflated 71%)
adding: jni/armeabi-v7a/libjnidispatch.so(in = 101596) (out= 42273)(deflated 58%)
adding: jni/armeabi-v7a/libmonodroid.so(in = 124668) (out= 54175)(deflated 56%)
adding: jni/armeabi-v7a/libmonosgen-2.0.so(in = 3432440) (out= 1438062)(deflated 58%)
adding: jni/x86/(in = 0) (out= 0)(stored 0%)
adding: jni/x86/libHelloWorld.so(in = 26716) (out= 9308)(deflated 65%)
adding: jni/x86/libjnidispatch.so(in = 99392) (out= 41165)(deflated 58%)
adding: jni/x86/libmonodroid.so(in = 157376) (out= 54453)(deflated 65%)
adding: jni/x86/libmonosgen-2.0.so(in = 3461060) (out= 1393699)(deflated 59%)
adding: jni/x86_64/(in = 0) (out= 0)(stored 0%)
adding: jni/x86_64/libHelloWorld.so(in = 32208) (out= 9160)(deflated 71%)
adding: jni/x86_64/libjnidispatch.so(in = 97688) (out= 39913)(deflated 59%)
adding: jni/x86_64/libmonodroid.so(in = 154200) (out= 55603)(deflated 63%)
adding: jni/x86_64/libmonosgen-2.0.so(in = 3635672) (out= 1535483)(deflated 57%)
```

I _think_ the iOS team is busy working on new Xcode/iOS 11, so I don't know when they will be back to help on Embeddinator.

I will add an F# project to our test suite so it will be easier for them to look into this when they do come back. Do you have an F# file that causes the original error? I can add that to the test as well.

**Comment by kylekurz** [comment] 2017-08-02 20:13
@jonathanpeppers nice to know it works for Android. I hadn't tried that platform yet, as I was primarily interested in iOS, right now. I have an F# project that causes the error, I'll try to look at it tomorrow when I'm back in the office. I'll have to share that manually, as it's company proprietary code instead of a trivial repro case.

**Comment by realvictorprm** [comment] 2017-08-02 21:50
Already 3 months passed and I didn't fix it yet. Time flows.... 

Tomorrow evening I may have time for this.

**Comment by chamons** [comment] 2018-03-19 21:41
Possibly related to https://github.com/mono/Embeddinator-4000/issues/549

**Comment by chamons** [comment] 2018-03-21 19:59
This appears to be a duplicate of https://github.com/mono/Embeddinator-4000/issues/549 as @jonathanpeppers showed it works for Android and I can reproduce it with the most trivial XM example. 

I'm going to close this for now, if your use case extends beyond objc and this is broken feel free to reopen.

**Closed by chamons** 2018-03-21 19:59 UTC
Labels: objc
