### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by Sam-Kruglov** [mono/Embeddinator-4000#793] opened 2021-05-08 09:24 UTC
We need to reopen #788 because the link in the readme still leads to nothing. The link you provided in the duplicate issue leads to an archived github repository. Why did Microsoft remove the .NET Embedding articles from Xamarin Tools documentation page?

I was only able to find the release notes about .net embedding 0.4 for which you have a branch 0.4 but it’s behind master. https://docs.microsoft.com/en-Us/xamarin/tools/dotnet-embedding/release-notes/preview/0.4

https://stackoverflow.com/questions/46520285/convert-net-standard-class-library-to-native-aar-jar

Could you clarify whether this project is production ready, being maintained, and has documentation?

**Comment by spouliot** [comment] 2021-05-10 14:30
> We need to reopen #788 

Np, issue #788 was closed as a dupe of https://github.com/mono/Embeddinator-4000/issues/786 which is still open.

> Could you clarify whether this project is production ready, 

The mono embedding API has been used in many successful project over the years. As such the underlying code base is production ready.

The tool itself is not mean to be used in production. The main goal of the embeddinator tool is to "produce _most_ of the boilerplate code" that is needed for interoperability. If something is not supported you have the choice of:
* implementing it directly with the mono embedding API;
* adding support to the tool to produce it (and the open a PR with your changes)

> being maintained, 

At this time the project is not actively maintained. Most engineering efforts are focused on .net 6. 

> and has documentation?

Minimally, thru mono embedding documentation.

**Closed as completed by spouliot** 2021-05-10 14:30 UTC
Labels: duplicate, question
