### ISSUE TITLE
[Android] MonoAndroidToolsPath path is not found

### ISSUE THREAD

**Issue by jasin755** [mono/Embeddinator-4000#531] opened 2017-10-30 09:09 UTC
After update to VisualStudio for Mac 8.1.xxx I got this error:

```
Parsing assemblies...
MonoAndroidToolsPath path is not found and no default location is provided; skipping.
```

**Comment by tritao** [comment] 2017-10-30 11:59
You mean after you upgraded to Xamarin.Android 8.1 right?

I can only find VS for Mac up to 7.3 in alpha channel.

**Comment by jasin755** [comment] 2017-10-30 12:05
Yes,  Xamarin.Android 8.1 from beta channel.

**Comment by jonathanpeppers** [comment] 2017-10-30 13:14
I'll try this and see what I find, thanks.

@jasin755 are you using Embeddinator from NuGet or building it from source?

**Comment by jasin755** [comment] 2017-10-30 13:45
I am using E4k from nugget and source with same error.

**Comment by jonathanpeppers** [comment] 2017-10-30 20:49
Hi @jasin755, I tried the beta channel and it is working for me.

It looks like Embeddinator starts from the directory where `Embeddinator-4000.exe` is found and looks upward, looking for `external/Xamarin.Android`.

Relevant code [here ](https://github.com/mono/Embeddinator-4000/blob/master/binder/Utils/XamarinAndroid.cs#L44)and [here](https://github.com/mono/Embeddinator-4000/blob/master/binder/Utils/Utils.cs#L77).

If that is not found, it uses your system Xamarin.Android, which would probably fail.

Can you tell if there is a valid `external/Xamarin.Android` directory that it _should_ be able to find?

**Comment by equinox2k** [comment] 2017-10-31 22:40
Been having same issue tried all sorts by trying to set working directory...

it looks like from first glance...

public static void Refresh (string runtimePath = null, string binPath = null, string bclPath = null)
	
(being called with Refresh())

which calls sdk.Initialize (runtimePath, binPath, bclPath);

which then uses FindRuntime is not using the working directory as a search path

e..g 		readonly static string[] SearchPaths = {
			"/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/mandroid",
			"/Developer/MonoAndroid/usr/lib/mandroid",
			"/app/lib/mandroid",
			"/opt/mono-android/lib/mandroid"
		};

However

I tried adding an export for MONO_ANDROID_PATH to point to the nuget tools directory and copying external and Xamarin.Android folder into various places with no luck..

**Comment by jonathanpeppers** [comment] 2017-11-01 03:41
The `external/Xamarin.Android` directory _was_ a temporary solution until Xamarin.Android 8.0 hit stable. I'm going to focus on just getting rid of it and using your system's Xamarin.Android, but it might take a little while.

@equinox2k can you send a zip of your project that reproduces it not finding `external/Xamarin.Android`? The short of it is that it should not even be hitting `MonoDroidSdk.BinPath`, and should find `external/Xamarin.Android`: https://github.com/mono/Embeddinator-4000/blob/fee60405c959a9ebcd18df905bc60ab9044e719c/binder/Utils/XamarinAndroid.cs#L44-L46

It looks like does the following to find it:
- `typeof(Helpers).Assembly.Location` then three directories up
- Current directory, then three directories up

If installed from NuGet that seems like it would always work. Unless there is a random issue extracting the package. It is a large package (~94MB), due to it including Xamarin.Android.

**Comment by equinox2k** [comment] 2017-11-01 05:49
@jonathanpeppers 

Here is a very simple project that shows problem... 
https://www.dropbox.com/s/xrku8ygk33myito/Repro.zip?dl=0

Open solution and build PNI.Photo.Library.Embedded.Droid this should start off the embeddinator process with error as above.

FYI visual studio 7.3 preview build 708 (beta channel)

**Comment by jonathanpeppers** [comment] 2017-11-02 02:36
@equinox2k I got your sample to work by changing the following:
- `TargetFrameworkVersion` has to be 7.1 or lower (the bundled Xamarin.Android does not have API O support)
- `AndroidUseLatestPlatformSdk` should be `False`, or it will make the project 8.0
- I replaced the Embeddinator 0.3.0 from NuGet with the latest I built on master

Here is your fixed project: https://www.dropbox.com/s/s0z5rmww8u7lyf0/Repro_fixed.zip?dl=0

I believe there are some fixes on master from PR #525 that solve the `MonoAndroidToolsPath path is not found` issue.

@jasin755 can you also try replacing your Embeddinator with the one in the zip above?

**Comment by equinox2k** [comment] 2017-11-02 16:54
@jonathanpeppers got it working now thanks for your help

**Comment by jonathanpeppers** [comment] 2017-11-02 17:08
@jasin755 closing this, as I think it is fixed on master. A new release is probably due soon, but I don't know the details of when that will be.

Feel free to reopen, if you find something else.

**Closed by jonathanpeppers** 2017-11-02 17:08 UTC
Labels: bug
