### ISSUE TITLE
What is the status of the project?

### ISSUE THREAD

**Issue by ILAgent** [mono/Embeddinator-4000#776] opened 2020-05-25 19:26 UTC
Is it an official and supporting approach for embedding .Net? Or the project is done and won't  develop more?

**Comment by chamons** [comment] 2020-05-27 21:17
This is a duplicate of https://github.com/mono/Embeddinator-4000/issues/758 , though you couldn't have easily seen that since it was closed. I'll copy the text here:


> There currently is not active development by members of the Xamarin team, but we are triaging incoming issues and assisting where it makes sense.
> 
> As a community project, the hope is that people will be able to build upon it to bundle C# libraries in native libraries. However, to do so today does involve getting your hands dirty by creating simplified "facade" interfaces in places.

**Closed by chamons** 2020-05-27 21:17 UTC
